import { fileURLToPath } from 'node:url'
import { defineVitestProject } from '@nuxt/test-utils/config'
import { defineConfig } from 'vitest/config'

function dir(path: string) {
  return fileURLToPath(new URL(path, import.meta.url))
}

// Tests may be colocated next to source (`app/**`) or grouped under `test/**`.
function nuxtProject(name: string, root: string, appName: string) {
  return defineVitestProject({
    test: {
      name,
      environment: 'nuxt',
      include: [`${root}/app/**/*.spec.ts`, `${root}/test/**/*.spec.ts`],
      exclude: ['**/*.server.spec.ts', '**/node_modules/**'],
      // Each spec file runs in its own worker and bootstraps the Nuxt app via
      // `@nuxt/test-utils`'s `beforeAll`, which easily exceeds Vitest's 10s
      // default on a loaded CI runner. Give it the same headroom as the e2e
      // projects so a slow bootstrap doesn't randomly fail the build.
      hookTimeout: 60_000,
      environmentOptions: {
        nuxt: {
          rootDir: dir(root),
          overrides: {
            runtimeConfig: {
              public: {
                appName,
                apiBase: 'http://api.test',
                apiVersion: 'v1',
                webUrl: 'http://web.test',
                appUrl: 'http://app.test',
                adminUrl: 'http://admin.test',
              },
            },
          },
        },
      },
    },
  })
}

export default defineConfig({
  test: {
    // Coverage is collected process-wide, so it is configured here (on the root
    // config) rather than inside the individual projects. Run `pnpm test:coverage`.
    coverage: {
      provider: 'v8',
      reporter: ['text', 'html', 'lcov'],
      reportsDirectory: './coverage',
      include: [
        'apps/*/app/**/*.{ts,vue}',
        'apps/*/server/**/*.ts',
        'packages/*/app/**/*.{ts,vue}',
        'packages/*/server/**/*.ts',
        'packages/*/src/**/*.{ts,vue}',
        'packages/config/index.ts',
        'packages/logger/index.ts',
      ],
      exclude: [
        '**/*.spec.ts',
        '**/*.test.ts',
        '**/*.d.ts',
        '**/.nuxt/**',
        '**/.output/**',
        '**/node_modules/**',
        // Entry shells: the Nuxt root component is a one-line layout wrapper.
        'apps/*/app/app.vue',
        'packages/*/app/app.vue',
        // Generated by `db:auth:generate`; its uncovered lines are `$onUpdate`
        // callbacks that only run on UPDATE queries.
        'apps/api/server/database/auth-schema.ts',
        // CLI script with top-level side effects, not runtime behavior.
        'apps/api/server/database/seed.ts',
      ],
      // E2E runs the built server in a child process, so V8 cannot see route
      // handlers there; route coverage comes from in-process handler specs.
      // Baseline after those specs is ~95%+; the floor is kept a little lower
      // so small additions don't red the build. Raise it (or use
      // `thresholds.autoUpdate`) as coverage improves.
      thresholds: {
        lines: 90,
        functions: 90,
        branches: 90,
        statements: 90,
      },
    },
    projects: [
      {
        define: { 'import.meta.server': true },
        test: {
          name: 'unit',
          environment: 'node',
          include: [
            'test/**/*.spec.ts',
            'packages/{config,types,logger}/test/**/*.spec.ts',
            'apps/api/server/**/*.spec.ts',
            'packages/client/app/**/*.server.spec.ts',
          ],
        },
      },
      {
        test: {
          name: 'api',
          environment: 'node',
          include: ['apps/api/test/e2e/**/*.spec.ts'],
          hookTimeout: 180_000,
          testTimeout: 60_000,
          env: {
            DATABASE_URL: 'postgres://test:test@localhost:5432/test',
            REDIS_URL: 'redis://localhost:6379',
            BETTER_AUTH_URL: 'http://localhost:3003',
            BETTER_AUTH_SECRET: 'test-secret-test-secret-test-secret',
            RATE_LIMIT_ENABLED: 'false',
          },
        },
      },
      {
        test: {
          name: 'api-dev',
          environment: 'node',
          include: ['apps/api/test/e2e-dev/**/*.spec.ts'],
          hookTimeout: 180_000,
          testTimeout: 60_000,
          env: {
            DATABASE_URL: 'postgres://test:test@localhost:5432/test',
            REDIS_URL: 'redis://localhost:6379',
            BETTER_AUTH_URL: 'http://localhost:3003',
            BETTER_AUTH_SECRET: 'test-secret-test-secret-test-secret',
            RATE_LIMIT_ENABLED: 'false',
          },
        },
      },
      await nuxtProject('ui', 'packages/ui', 'web'),
      await nuxtProject('client', 'packages/client', 'app'),
      await nuxtProject('web', 'apps/web', 'web'),
      await nuxtProject('app', 'apps/app', 'app'),
      await nuxtProject('admin', 'apps/admin', 'admin'),
    ],
  },
})
